# Site settings
title: Ryan Armstrong's Blog
email: ryan@cavaliercoder.com
description: >
    Interneting all the thoughts with varying levels of validity and accuracy.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cavaliercoder.github.io" # the base hostname & protocol for your site
twitter_username: cavaliercoder
github_username:  cavaliercoder

# Build settings
markdown: kramdown

categories: blog
permalink: /blog/:title.html

disqus_shortname: ryanarmstrongnetau
