# Site settings
title: Ryan Armstrong's Blog
email: ryan@cavaliercoder.com
description: >
    The poorly maintained ramblings of an Infrastructure/Software engineer.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cavaliercoder.github.io" # the base hostname & protocol for your site
cdnurl: "http://cdn.cavaliercoder.com/blog"
twitter_username: cavaliercoder
github_username:  cavaliercoder

# Build settings
markdown: kramdown
permalink: /:categories/:title.html
disqus_shortname: ryanarmstrongnetau

include: [ ./_pages ]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      category: blog
